version: "3.7"

services:
  connector:
    container_name: connector
    image: registry.enmeshed.eu/bc:<tag-or-latest> # specify a tag (e.g. 1.0.0) or use the latest tag
    environment:
      DATABASE_CONNECTION_STRING: <mongodb-connection-string> # provide the connection string to your MongoDB
      ACCOUNT: <account-name> # define an account name here (useful for running multiple connectors on one MongoDB)
      API_KEY: <api-key> # choose a secure api key to communicate with the connector
      CLIENT_ID: "<client-id>" # the client id you received from the enmeshed support
      CLIENT_SECRET: "<client-secret>" # the client secret you received from the enmeshed support
    ports:
      - <exposed-port>:80 # define the port the connector should listen to on the host
    # volumes:
    #   - </folder/of/your/choice>:/usr/app/logs # select an existing directory of your choice where your log files should be saved
    restart: always
